name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Deno environment
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: latest

      - name: Install dependencies
        run: deno ci

      - name: Run lint check
        run: deno task lint

      - name: Run tests
        run: deno task test
